GET http://localhost:7000/

###

GET http://localhost:7000/about

###

GET http://localhost:7000/hotSauces

###
POST http://localhost:7000/hotSauces
Content-Type: application/json

{
  "name": "John's Special Sauce",
  "heatLevel": "1",
  "sauceInfo": "John's secret recipe"
}

###
PATCH http://localhost:7000/hotSauces/5aea789e40165d09933486da
Content-Type: application/json

{
  "name": "John's Actual Special Sauce",
  "heatLevel": "11",
  "sauceInfo": "jidofhudoifgiuhsiudes"
}

###
DELETE http://localhost:7000/hotSauces/5aea789e40165d09933486da